<?php
include('functions.php');
?>
<html>
    <head>
        <link rel='stylesheet' href='/~assign225/style/main.css'/>
        <link rel='icon' href='/~assign225/images/favicon.png'/>
        <title>PointsOfInterest</title>
    </head>
    <body>
        <div id='content'>
            <header>
                <?php navbar();?>
                <h1 id='title'>PointsOfInterest</h1>
            </header>
            <div id='main'>
                <table>
                <form method='post' action='<?php echo "/~assign225/"; echo htmlentities("$value");?>'>
                    <tr>
                        <td><label for='username'>Username:</label></td>
                        <td><input name='username' id='username' type='text'/></td>
                    </tr>
                    <tr>
                        <td><label for='password'>Password:</label></td>
                        <td><input name='password' id='password' type='password'/></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td><input name='action' type='submit' value='<?php echo ucfirst("$value");?>'/></td>
                    </tr>
                </form>
                </table>
            </div><!--[end]#main-->
        </div><!--[end]#content-->
    </body>
</html>
