<?php
include('functions.php');
?>
<html>
    <head>
        <link rel='stylesheet' href='/~assign225/style/main.css'/>
        <link rel='icon' href='/~assign225/images/favicon.png'/>
        <title>PointsOfInterest</title>
    </head>
    <body>
        <div id='content'>
            <header>
                <?php navbar();?>
                <h1 id='title'>PointsOfInterest</h1>
            </header>
            <div id='main'>
                <table>
                <form method='post' action='add_poi'>
                    <tr>
                        <td><label for='name'>Name: </label></td>
                        <td><input name='name' type='text' pattern='^[a-zA-Z,.-]+$' required/></td>
                    </tr>
                    <tr>
                        <td><label for='type'>Type: </label></td>
                        <td><select name='type'>
<?php
$types=array('Hotel','City','Historical Site','Bar','Pub','Restaurant','Beach','Mountain','Hill','Industrial Estate','Lost City','Moor','Port','Town','Village');
foreach ($types as $type){
    echo "<option value='$type'>$type</option>";
    }
echo "</td>";
?>
                    </tr>
                    <tr>
                        <td><label for='country'>Country: </label></td>
                        <td><select name='country'>
<?php
$countries=file('countries');
foreach ($countries as $country){
    echo "<option value='$country'>$country</option>";
    }
echo "</td>";
?>
                    </tr>
                    <tr>
                        <td><label for='region'>Region: </label></td>
                        <td><input name='region' type='text' pattern='^[a-zA-Z,.-]+$' required/></td>
                    </tr>
                    <tr>
                        <td><label for='lon'>Longitude: </label></td>
                        <td><input type='text' name='lon' maxlength='9' size='9' pattern='^(\+|-)?(?:180(?:(?:\.0{1,6})?)|(?:[0-9]|[1-9][0-9]|1[0-7][0-9])(?:(?:\.[0-9]{1,6})?))$' placeholder='0-180' required/></td>
                    </tr>
                    <tr>
                        <td><label for='lat'>Latitude: </label></td>
                        <td><input type='text' name='lat' maxlength='9' size='9' pattern='^(\+|-)?(?:90(?:(?:\.0{1,6})?)|(?:[0-9]|[1-8][0-9])(?:(?:\.[0-9]{1,6})?))$'placeholder='0-90' required/></td>
                    </tr>
                    <tr>
                        <td><label for='description'>Description: </label></td>
                        <td><input name='description' type='text' required/></td>
                    </tr>
                    <tr>
                        <td><input type='hidden' id='username' name='username' value='<?php echo $_SESSION['gatekeeper']?>'/></td>
                        <td><input name='submit' type='submit'/></td>
                    </tr>
                </form>
                </table>
            </div><!--[end]#main-->
        </div><!--[end]#content-->
    </body>
</html>
