<table>
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Type</th>
        <th>Country</th>
        <th>Region</th>
        <th>Lon</th>
        <th>Lat</th>
        <th>Description</th>
        <th>Recommended</th>
        <th>Username</th>
    </tr>
<?$row=$results->fetch(PDO::FETCH_ASSOC);
do{?>
    <tr>
        <td><?=$row['ID']?></td>
        <td><input type='submit' id='link' value='<?=$row['name']?>' onclick='poiRequest(<?=$row['ID']?>)'></td>
        <td><?=$row['type']?></td>
        <td><?=$row['country']?></td>
        <td><?=$row['region']?></td>
        <td><?=$row['lon']?></td>
        <td><?=$row['lat']?></td>
        <td><?=$row['description']?></td>
        <td><?=$row['recommended'];
            if (isset ($_SESSION['gatekeeper'])){
                echo "<input type='submit' onclick='recommend(".$row['ID'].")' value='Recommend'/>";
}?>
</td>
        <td><?=$row['username']?></td>
    </tr>
<?}while ($row=$results->fetch(PDO::FETCH_ASSOC))?>
</table>
