<?php
include('functions.php');
?>
<html>
    <head>
        <link rel='stylesheet' href='style/main.css'/>
        <link rel='icon' href='images/favicon.png'/>
        <title>PointsOfInterest</title>
    </head>
    <body>
        <div id='content'>
            <header>
                <?php navbar();?>
                <h1 id='title'>PointsOfInterest</h1>
            </header>
            <div id='main'>
                <nav>
<?poi_options();?>
<form method='get' action='/pointsofinterest/region'>
    <label>Search within region: </label>
    <select name='region'/>
<?php
while ($row=$regions->fetch(PDO::FETCH_ASSOC)){
?>
    <option value='<?echo $row['region']?>'><?echo $row['region']?></option>
<?}?>
    <input type='submit' value='Search'/>
</form>

                <table>
                    <tr>
                        <th>Name</th>
                        <th>Type</th>
                        <th>Country</th>
                        <th>Region</th>
                        <th>Longitude</th>
                        <th>Latitude</th>
                        <th>Description</th>
                        <th>Recommended</th>
                    </tr>
<?php
while ($row=$results->fetch(PDO::FETCH_ASSOC)){
?>
                    <tr>
                        <td>
<? if (!stripos($_SERVER['REQUEST_URI'], '/view/')){?>
   <a href='view/<?echo $row['ID'];?>'><?=$row['name']?></a></td>
<?}else{?>
   <?=$row['name']?></td>
<?}?>
                        <td><?=$row['type']?></td>
                        <td><?=$row['country']?></td>
                        <td><?=$row['region']?></td>
                        <td><?=$row['lon']?></td>
                        <td><?=$row['lat']?></td>
                        <td><?=$row['description']?></td>
                        <td><?=$row['recommended'];
if (stripos($_SERVER['REQUEST_URI'], '/view/') && isset($_SESSION['gatekeeper'])){?>
<form method='post' action='/pointsofinterest/recommend'>
<input type='hidden' name='ID' value='<?echo str_replace("'","",$row['ID']);?>'/>
<input type='submit' value='Recommend'/>
</form>
<?}?></td>
                    </tr>
<?php
}
?>
                </table>
            </div><!--[end]#main-->
        </div><!--[end]#content-->
    </body>
</html>
