<?php
include('functions.php');
?>
<html>
    <head>
        <link rel='stylesheet' href='style/main.css'/>
        <link rel='icon' href='images/favicon.png'/>
        <title>PointsOfInterest</title>
    </head>
    <body>
        <div id='content'>
            <header>
                <?php navbar();?>
                <h1 id='title'>PointsOfInterest</h1>
            </header>
            <div id='main'>
                <nav>
<?php if (isset($_SESSION['gatekeeper'])){?>
                    <nav><a href='add'>Add</a></nav>
<?}else{?>
                    <p>Login to get further functionality</p>
<?}?>

                <table>
                    <tr>
                        <th>Name</th>
                        <th>Type</th>
                        <th>Country</th>
                        <th>Region</th>
                        <th>Longitude</th>
                        <th>Latitude</th>
                        <th>Description</th>
                        <th>Recommended</th>
                    </tr>
<?php
while ($row=$results->fetch(PDO::FETCH_ASSOC)){
?>
                    <tr>
                        <td><?=$row['name']?></td>
                        <td><?=$row['type']?></td>
                        <td><?=$row['country']?></td>
                        <td><?=$row['region']?></td>
                        <td><?=$row['lon']?></td>
                        <td><?=$row['lat']?></td>
                        <td><?=$row['description']?></td>
                        <td><?=$row['recommended']?></td>
                    </tr>
<?php
}
?>
                </table>
            </div><!--[end]#main-->
        </div><!--[end]#content-->
    </body>
</html>
