<?php
include('functions.php');
?>
<html>
    <head>
        <link rel='stylesheet' href='/~assign225/style/main.css'/>
        <link rel='icon' href='/~assign225/images/favicon.png'/>
        <script type='text/javascript' src='/~assign225/script/ajax.js'></script>
        <title>PointsOfInterest</title>
    </head>
    <body>
        <div id='content'>
            <header>
                <?php navbar();?>
                <h1 id='title'>PointsOfInterest</h1>
            </header>
            <div id='main'>
                <nav>
                    <?poi_options(@$_SESSION['pageID']);?>
                <label>Search within region: </label>
                <select name='region' id='region'/>
<?while ($row=$regions->fetch(PDO::FETCH_ASSOC)){?>
    <option value='<?echo $row['region']?>'><?echo $row['region']?></option>
<?}?>
                <input type='submit' id='regionButton' value='Search'/>
                <div id='searchresults'></div>
                <div id='reviews'></div>
            </div><!--[end]#main-->
        </div><!--[end]#content-->
    </body>
</html>
