<?php
include('functions.php');
?>
<html>
    <head>
        <link rel='stylesheet' href='/~assign225/style/main.css'/>
        <link rel='icon' href='/~assign225/images/favicon.png'/>
        <title>PointsOfInterest</title>
    </head>
    <body>
        <div id='content'>
            <header>
                <?php navbar();?>
                <h1 id='title'>PointsOfInterest</h1>
            </header>
            <div id='main'>
                <table>
                <form method='post' action='/~assign225/review_poi'>
                    <tr>
                        <td><label for='review'/>Review: </label></td>
                        <td><textarea name='review' required></textarea></td>
                    </tr>
                    <tr>
<?php $row=$results->fetch(PDO::FETCH_ASSOC)?>
                        <td><input type='hidden' name='poi_id' value='<?php echo $row['ID']?>'/></td>
                        <td><input type='submit'/></td>
                    </tr>
                </form>
                </table>
            </div><!--[end]#main-->
        </div><!--[end]#content-->
    </body>
</html>
